name: Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ^14.18.16

      - name: Install
        run: yarn install

      - name: Format
        run: yarn fmt

      - name: Test
        run: yarn test
        continue-on-error: true
