name: Build

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [^14.18.16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install

      - name: Format
        run: yarn fmt

      - name: Test
        run: yarn test
